### ISSUE TITLE
music.youtube.com no longer providing a "/browse" POST request

### ISSUE THREAD

**Issue by joaorsbarbosa** [AatomiccB/transfer_between_spotify_and_ytmusic#3]
No longer can get the RequestHeader from music.youtube.com. The "/browse" search returns empty

**Comment by joaorsbarbosa** [comment]
Well, turns out that now simply the "/" was dropped. When I searched, using firefox, for browse, it returns. "browse?prettyPrint=false". Perhaps the read.me needs to be updated.

**Comment by YESNLars** [comment]
@joaorsbarbosa What do you mean, how can I get the RequestHeader data
